trigger:
  - master

variables:
  imageName: 'express-musicapi'

steps:
- task: Docker@2
  displayName: Build an image
  inputs:
    repository: $(imageName)
    command: build
    Dockerfile: express-main-example/Dockerfile